// app/src/models/access.model.ts

/**
 * access model
 * -----------------
 * This file defines the Sequelize `Access` model, which represents the `accesses` table in the database.
 *
 * It contains:
 * - Model attributes (`AccessAttributes`).
 * - Required attributes for creation (`AccessCreationAttributes`).
 * - Definition of the model with its columns and constraints.
 *
 * This model is used by services and controllers to perform CRUD operations.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Attributes for `Access`.
 */
export interface AccessAttributes {
    id_access: number;
    role_id: number;
    username: string;
    password: string;
    is_active: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

/**
 * Attributes used for creating a new access.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, as it is automatically generated by the database.
 */
export interface AccessCreationAttributes extends Optional<AccessAttributes, "id_access"> { }

/**
 * Class that represents the `Access` model in Sequelize.
 *
 * Implements the attributes defined in `AccessAttributes` and `AccessCreationAttributes`.
 */
class Access extends Model<AccessAttributes, AccessCreationAttributes> implements AccessAttributes {

    public id_access!: number;
    public role_id!: number;
    public username!: string;
    public password!: string;
    public is_active!: boolean;
    public createdAt!: Date;
    public updatedAt!: Date;
}

/**
 * Initialization of the `Access` model with Sequelize configuration.
 *
 * - `id_access`: Auto-incrementing integer, primary key.
 * - `username`: User for logging in.
 * - `password`: Password for logging in.
 * - `is_active`: Boolean to determine if the access is active or inactive.
 */
Access.init(
    {
        id_access: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        role_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "roles",
                key: "id_role",
            },
        },
        username: {
            type: DataTypes.STRING(50),
            unique: true,
            allowNull: false,
        },
        password: {
            type: DataTypes.STRING(255),
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Access",   
        tableName: "accesses",  
        timestamps: true,      
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Access;
