// app/src/models/bank.model.ts

/**
 * Bank model
 * -----------------
 * This file defines the Sequelize `Bank` model, which represents the `banks` table in the database.
 *
 * It contains:
 * - Model attributes (`BankAttributes`).
 * - Required attributes for creation (`BankCreationAttributes`).
 * - Definition of the model with its columns and constraints.
 *
 * This model is used by services and controllers to perform CRUD operations.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Attributes for `Bank`.
 */
export interface BankAttributes {
    id_bank: number;
    name: string;
    is_active: boolean;
}

/**
 * Attributes used for creating a new bank.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, as it is automatically generated by the database.
 */
export interface BankCreationAttributes extends Optional<BankAttributes, "id_bank"> { }

/**
 * Class that represents the `Bank` model in Sequelize.
 *
 * Implements the attributes defined in `BankAttributes` and `BankCreationAttributes`.
 */
class Bank extends Model<BankAttributes, BankCreationAttributes> implements BankAttributes {
    /** Unique identifier of the bank (primary key). */
    public id_bank!: number;

    /** Bank name */
    public name!: string;

    /** State in which the bank is (active/inactive) */
    public is_active!: boolean;
}

/**
 * Initialization of the `Bank` model with Sequelize configuration.
 *
 * - `id_bank`: Auto-incrementing integer, primary key.
 * - `name`: Bank name with a maximum of 100 characters.
* - `is_active`: Boolean to determine if the bank is active or inactive.
*/
Bank.init(
    {
        id_bank: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Bank",      
        tableName: "banks",     
        timestamps: true,      
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Bank;
