// app/src/models/category.model.ts

/**
 * Category Model
 * -----------------
 * This file defines the Sequelize `Category` model, which represents the `categories` table in the database..
 * 
 * Contains:
 *  - model atributes (`CategoryAttributes`).
 *  - Attributes required for creation (`CategoryCreationAttributes`).
 *  - Defining the model with its columns and restrictions.
 * 
 * This model is used by services and controllers to perform CRUD operations..
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the entity `Category`.
 */
export interface CategoryAttributes {
  id_category: number;
  name: string;
  is_active: boolean;
}

/**
 * Attributes used for the creation of a new Category.
 * 
 * `Optional` is used to indicate that `id_Category` is not currently required.
 * of creation, since it is automatically generated by the database.
 */
export interface CategoryCreationAttributes extends Optional<CategoryAttributes, "id_category" > {}

/**
 * Class that represents the `Category` model in Sequelize.
 * 
 * Implements the attributes defined in `CategoryAttributes` and `CategoryCreationAttributes`.
 */
class Category extends Model<CategoryAttributes, CategoryCreationAttributes> implements CategoryAttributes {
  /** Unique Category identifier (primary key). */
  public id_category!: number;

  /** Category name. */
  public name!: string;

  /** State in which the Category is located (active/inactive) */
  public is_active!: boolean;

}

/**
 * Initializing the `Category` model with Sequelize configuration.
 * 
 * - `id_Category`: Auto-incrementing integer, primary key.
 * - `name`: Unique and mandatory Category name with a maximum of 100 characters.
 * - `is_active`: Boolean to determine whether the Category is active or inactive.
 */
Category.init(
  {
    id_category: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING(100),
      unique: true,
      allowNull: false,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },
  {
    sequelize,
    modelName: "Category",      // Model name in Sequelize
    tableName: "categories",     // Name of the table in the database
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default Category;
