// app/src/models/city.model.ts

/**
 * City Model
 * -----------------
 * This file defines the Sequelize `City` model, which represents the `cities` table in the database.
 *
 * 
 * Contains:
 * - Model attributes (`CityAttributes`).
 * - Attributes required for creation (`CityCreationAttributes`).
 * - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `City` entity.
 */
export interface CityAttributes {
    id_city: number;
    name: string;
    is_active: boolean;
}

/**
 * Attributes used for creating a new city.
 * `Optional` is used to indicate that `id_city` is not required at the time of creation, as it is automatically generated by the database.
 */
export interface CityCreationAttributes extends Optional<CityAttributes, "id_city"> { }

/**
 * Class that represents the `City` model in Sequelize.
 * 
 * Implements the attributes defined in `CityAttributes` and `CityCreationAttributes`.
 */
class City extends Model<CityAttributes, CityCreationAttributes> implements CityAttributes {
    /** Unique user identifier (primary key). */
    public id_city!: number;

    /** City name */
    public name!: string;

    /** State in which the city is located (active/inactive) */
    public is_active!: boolean;
}

/**
 * Initialization of the `City` model with the Sequelize configuration.
 * 
 * - `id_city`: Auto-incrementing integer, primary key.
 * - `name`: City name, up to 100 characters.
 * - `is_active`: Boolean to determine whether the city is active or inactive.
 */
City.init(
    {
        id_city: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "City",      // Model name in Sequelize
        tableName: "cities",     // Name of the table in the database
        timestamps: true,      // includes createdAt and updatedAt
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default City;
