// app/src/models/contry.model.ts

/**
 * Country Model
 * -----------------
 * This file defines the Sequelize `Country` model, which represents the `countries` table in the database..
 * 
 * Contains:
 *  - model atributes (`CountryAttributes`).
 *  - Attributes required for creation (`CountryCreationAttributes`).
 *  - Defining the model with its columns and restrictions.
 * 
 * This model is used by services and controllers to perform CRUD operations..
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the entity `Country`.
 */
export interface CountryAttributes {
  id_country: number;
  name: string;
  is_active: boolean;
}

/**
 * Attributes used for the creation of a new country.
 * 
 * `Optional` is used to indicate that `id_country` is not currently required.
 * of creation, since it is automatically generated by the database.
 */
export interface CountryCreationAttributes extends Optional<CountryAttributes, "id_country" > {}

/**
 * Class that represents the `Country` model in Sequelize.
 * 
 * Implements the attributes defined in `CountryAttributes` and `CountryCreationAttributes`.
 */
class Country extends Model<CountryAttributes, CountryCreationAttributes> implements CountryAttributes {
  /** Unique country identifier (primary key). */
  public id_country!: number;

  /** Country name. */
  public name!: string;

  /** State in which the country is located (active/inactive) */
  public is_active!: boolean;

}

/**
 * Initializing the `Country` model with Sequelize configuration.
 * 
 * - `id_country`: Auto-incrementing integer, primary key.
 * - `name`: Unique and mandatory country name with a maximum of 100 characters.
 * - `is_active`: Boolean to determine whether the country is active or inactive.
 */
Country.init(
  {
    id_country: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING(100),
      unique: true,
      allowNull: false,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },
  {
    sequelize,
    modelName: "Country",      // Model name in Sequelize
    tableName: "countries",     // Name of the table in the database
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default Country;
