// app/src/models/departmen.model.ts

/**
 * Department Model
 * -----------------
 * This file defines the Sequelize `Department` model, which represents the `departments` table in the database.
 * 
 * It contains:
 * - Model attributes (`DepartmentAttributes`).
 * - Attributes required for creation (`DepartmentCreationAttributes`).
 * - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `Department` entity.
 */
export interface DepartmentAttributes {
    id_department: number;
    name: string;
    is_active: boolean;
}

/**
 * Attributes used to create a new department.
 * `Optional` is used to indicate that `department_id` is not required at the time of creation, as it is automatically generated by the database.
  */
export interface DepartmentCreationAttributes extends Optional<DepartmentAttributes, "id_department"> { }

/**
 * Class that represents the `Department` model in Sequelize.
 * Implements the attributes defined in `DepartmentAttributes` and `DepartmentCreationAttributes`.
 */
class Department extends Model<DepartmentAttributes, DepartmentCreationAttributes> implements DepartmentAttributes {
    /** Unique user identifier (primary key). */
    public id_department!: number;

    /** Department name. */
    public name!: string;

    /** State in which the department is located (active/inactive) */
    public is_active!: boolean;

}

/**
 * Initialization of the `Department` model with the Sequelize configuration.
 * 
 * - `id_departament`: Auto-incrementing integer, primary key.
 * - `name`: Department name, maximum 100 characters.
 * - `is_active`: Boolean to determine whether the department is active or inactive.
 */
Department.init(
    {
        id_department: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Department",      // Model name in Sequelize
        tableName: "departments",    // Name of the table in the database
        timestamps: true,             // incluye createdAt y updatedAt
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Department;
