// app/src/models/gender.model.ts

/**
 * Gender Model
 * -----------------
 * This file defines the Sequelize  `Gender` model, which represents the  `Gender` table in the database.
 *
 * Contains:
 *  - Model attributes ( `GenderAttributes`).
 *  - Required attributes for creation ( `GenderCreationAttributes`).
 *  - Model definition with its columns and constraints.
 *
 * This model is used by the services and controllers to perform CRUD operations.
 */
import { DataTypes,Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `Gender` entity.
 */

export interface GenderAttributes {
    id_gender : number;
    name : string;
    is_active : boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

/**
 * Attributes used for creating a new Gender.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, since it is automatically generated by the database.
 */

export interface GenderCreationAttributes extends Optional<GenderAttributes, "id_gender"> { }

/**
 * Class that represents the `Gender` model in Sequelize.
 * 
 * Implements the attributes defined in  `GenderAttributes` and  GenderCreationAttributes`.
 */
class Gender extends Model<GenderAttributes, GenderCreationAttributes> implements GenderAttributes { 
    public id_gender!: number;
    public name!: string;
    public is_active!: boolean;
    public createdAt!: Date;
    public updatedAt!: Date;
}

/**
 * Initialization of the `Gender` model with Sequelize configuration.
 * 
 * - `id_gender`: Auto-increment integer, primary key.
 * - `name`: User for login.
 * - `is_active`: Boolean to determine whether the account is active or inactive.
 */
Gender.init(
    {
        id_gender:{
            type:DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name:{
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
        is_active: {
            type:DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Gender", //Name of model in Sequelize
        tableName: "genders",  // Name of table in the database
        timestamps : true, // Include createdAt and updatedAt
        createdAt : "created_at",
        updatedAt : "updated_at"


    }
)

export default Gender;