// app/src/models/order.model.ts

/**
 * Order Model
 * -----------------
 * This file defines the Sequelize `Order` model, which represents the `orders` table in the database..
 * 
 * Contains:
 *  - model atributes (`OrderAttributes`).
 *  - Attributes required for creation (`OrderCreationAttributes`).
 *  - Defining the model with its columns and restrictions.
 * 
 * This model is used by services and controllers to perform CRUD operations..
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the entity `Order`.
 */
export interface OrderAttributes {
  id_order: number;
  customer_id: number;
  bank_id: number;
  order_status_id: number;
  total: number;
  is_active: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Attributes used for the creation of a new Order.
 * 
 * `Optional` is used to indicate that `id_order` is not currently required.
 * of creation, since it is automatically generated by the database.
 */
export interface OrderCreationAttributes extends Optional<OrderAttributes, "id_order" > {}

/**
 * Class that represents the `Order` model in Sequelize.
 * 
 * Implements the attributes defined in `OrderAttributes` and `OrderCreationAttributes`.
 */
class Order extends Model<OrderAttributes, OrderCreationAttributes> implements OrderAttributes {
  /** Unique Order identifier (primary key). */
  public id_order!: number;

  /** Order customer. */
  public customer_id!: number;

  /** Order bank. */
  public bank_id!: number;

  /** Order status. */
  public order_status_id!: number;

   /** Order total. */
  public total!: number; 

  /** State in which the Order is located (active/inactive) */
  public is_active!: boolean;
  
  public createdAt!: Date;
  public updatedAt!: Date;

}

/**
 * Initializing the `Order` model with Sequelize configuration.
 * 
 * - `id_order`: Auto-incrementing integer, primary key.
 * - `name`: Unique and mandatory Order name with a maximum of 100 characters.
 * - `is_active`: Boolean to determine whether the Order is active or inactive.
 */
Order.init(
  {
    id_order: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    customer_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "accesses",
        key: "id_access",
      }
    },
      bank_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "banks",
        key: "id_bank",
        }
    },
     order_status_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "order_status",
        key: "id_order_status",
        }
    },
    total: {
      type: DataTypes.DECIMAL(12, 2),
      allowNull: false,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },

  {
    sequelize,
    modelName: "Order",      // Model name in Sequelize
    tableName: "orders",     // Name of the table in the database
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default Order;
