// app/src/models/role.model.ts

/**
/**
 * Role Model
 * ----------
 * This file defines the Sequelize `Role` model, which represents the `roles` table in the database.
 *
 * 
 * Contains:
 *  - Model attributes (`RoleAttributes`).
 *  - Required attributes for creation (`RoleCreationAttributes`).
 *  - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */


import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 *  Main attributes of the `Role` entity.
 */
export interface RoleAttributes {
    id_role: number;
    name: string;
    is_active: boolean;
}

/**
 * Attributes used for creating a new Role.
 * `Optional` is used to indicate that `id` is not required at the time
 * of creation, as it is automatically generated by the database.
 */

export interface RoleCreationAttributes extends Optional<RoleAttributes, "id_role"> { }

/**
 * Class that represents the `Role` model in Sequelize.
 * 
 * Implements the attributes defined in `RoleAttributes` and `RoleCreationAttributes`.
 */

class Role extends Model<RoleAttributes, RoleCreationAttributes> implements RoleAttributes {
    /** Unique identifier of the role (primary key). */

    public id_role!: number;

    /** Name of the role */

    public name!: string;

    /** Status of the role (active/inactive) */

    public is_active!: boolean;
}

/**
 * Initialization of the `Role` model with Sequelize configuration.
 * 
 * - `id`: Auto-incrementing integer, primary key.
 * - `name`: Name of the role with a maximum of 100 characters.
 * - `is_active`: Boolean to indicate whether the role is active or inactive.
 */

Role.init(
    {
        id_role: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING(100),
            unique: true,
            allowNull: false,
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Role",      // Name of the model in Sequelize
        tableName: "roles",     // Name of the table in the database
        timestamps: true,       // includes createdAt and updatedAt
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Role;
