// app/src/models/user.model.ts

/**
 * User Model
 * -----------------
 * This file defines the Sequelize `User` model, which represents the `users` table in the database.
 * 
 * It contains:
 * - Model attributes (`UserAttributes`).
 * - Attributes required for creation (`UserCreationAttributes`).
 * - Model definition with its columns and constraints.
 * 
 * This model is used by services and controllers to perform CRUD operations.
 */

import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `User` entity.
 */
export interface UserAttributes {
  id_user: number;
  access_id: number;
  gender_id: number;
  full_name: string;
  email: string;
  birth_date: Date;
  phone: string;
  is_active: boolean;
}

/**
 * Attributes used for creating a new user.
 * 
 * `Optional` is used to indicate that `id_user` is not required at the time of creation, as it is automatically generated by the database.
 */
export interface UserCreationAttributes extends Optional<UserAttributes, "id_user" > {}

/**
 * Class that represents the `User` model in Sequelize.
 * 
 * Implements the attributes defined in `UserAttributes` and `UserCreationAttributes`.
 */
class User extends Model<UserAttributes, UserCreationAttributes> implements UserAttributes {
  /** Unique user identifier (primary key). */
  public id_user!: number;
  
  /** User access identifier (foreign key). */
  public access_id!: number;
  
  /** User gender identifier (foreign key). */
  public gender_id!: number;

  /** Full name of the user's username. */
  public full_name!: string;

  /** Unique email address of the user. */
  public email!: string;

  /** User's date of birth. */
  public birth_date!: Date;

  /** User's phone number. */
  public phone!: string;

  /** State in which the user is (active/inactive) */
  public is_active!: boolean;
}

/**
 * Initialization of the `User` model with the Sequelize configuration.
 * 
 * - `id_user`: Auto-incrementing integer, primary key.
 * - `access_id`: Integer, foreign key.
 * - `gender_id`: Integer, foreign key.
 * - `full_name`: User's full name, with a maximum of 100 characters.
 * - `email`: A unique and mandatory email address, with a maximum of 100 characters.
 * - `birth_date`: User's birthday.
 * - `phone`: User's phone number, with a maximum of 20 characters.
 * - `is_active`: A Boolean to determine whether the user is active or inactive.
 */
User.init(
  {
    id_user: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    access_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "accesses",
        key: "id_access",
      },
    },
    gender_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "genders",
        key: "id_gender",
      },
    },
    full_name: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING(100),
      unique: true,
      allowNull: false,
    },
    birth_date: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    phone: {
      type: DataTypes.STRING(20),
      allowNull: true,
    },
    is_active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
    }
  },
  {
    sequelize,
    modelName: "User",      // Model name in Sequelize
    tableName: "users",     // Name of the table in the database
    timestamps: true,      // includes createdAt and updatedAt
    createdAt: "created_at",
    updatedAt: "updated_at"
  }
);

export default User;
